In [10]:
import torch
from lerobot.common.datasets.lerobot_dataset import LeRobotDataset


In [11]:
repo_id = "iantc104/testing"
dataset = LeRobotDataset.create(
    repo_id=repo_id,
    root=f"outputs/{repo_id}",
    fps=33,
    features={
        "left_arm_pose": {
            "dtype": "float32",
            "shape": (16,),
            "names": None,
        },
        "right_arm_pose": {
            "dtype": "float32",
            "shape": (16,),
            "names": None,
        },
    },
    image_writer_threads=10,
    image_writer_processes=5,
)




In [13]:
for i in range(10):
    dataset.add_frame({
        "left_arm_pose": torch.randn(16),  # Example data, replace with actual data
        "right_arm_pose": torch.zeros(16),  # Example data, replace with actual data
    }, task="test")


In [15]:
dataset.episode_buffer['left_arm_pose'] = [torch.zeros(16) for _ in range(10)]
dataset.episode_buffer

{'size': 10,
 'task': ['test',
  'test',
  'test',
  'test',
  'test',
  'test',
  'test',
  'test',
  'test',
  'test'],
 'left_arm_pose': [tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])],
 'right_arm_pose': [array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        

In [16]:
dataset.save_episode()

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

In [ ]:
dataset = LeRobotDataset.create(
    repo_id=repo_id,
    root=f"outputs/{repo_id}",
    fps=33,
    features={
        "left_arm_pose": {
            "dtype": "float32",
            "shape": (16,),
            "names": None,
        },
        "right_arm_pose": {
            "dtype": "float32",
            "shape": (16,),
            "names": None,
        },
    },
    image_writer_threads=10,
    image_writer_processes=5,
)